# ABSOLUTELY FINAL COMPLETE CONFIG - ALL SECTIONS INCLUDED

# Project configuration
project:
  name: "SE Word Embeddings Comparison"
  version: "1.0.0"
  description: "Comparison of Word2Vec and ModernBERT for Software Engineering domain"

# System configuration
system:
  log_level: INFO
  random_seed: 42
  device: auto

# Paths configuration
paths:
  data_raw: "results/data/raw"
  data_processed: "results/data/processed"
  models: "results/models"
  evaluations: "results/evaluations"
  reports: "results/reports"
  figures: "results/figures"
  logs: "results/logs"

# Logging configuration
logging:
  level: INFO
  file: "results/logs/se_embeddings.log"
  console: true
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size: "10MB"
  backup_count: 5

# Models configuration
models:
  word2vec:
    enabled: true
    vector_size: 50
    window: 3
    min_count: 1
    workers: 2
    epochs: 3
    sg: 0
    hs: 0
    negative: 5
    alpha: 0.025
    min_alpha: 0.0001
    batch_size: 1000
    max_vocab_size: 5000

  modernbert:
    enabled: true
    model_name: "answerdotai/ModernBERT-base"
    max_length: 128
    batch_size: 2
    learning_rate: 2e-5
    num_epochs: 1
    warmup_steps: 10
    weight_decay: 0.01
    save_steps: 50
    eval_steps: 25
    logging_steps: 5
    gradient_accumulation_steps: 1
    fp16: false
    early_stopping_patience: 2
    early_stopping_threshold: 0.001

# Data collection configuration
data_collection:
  wikipedia:
    enabled: true
    max_articles: 5
  github:
    enabled: true
    max_repos: 3
  stackoverflow:
    enabled: true
    max_posts: 5
  arxiv:
    enabled: true
    max_papers: 2

# Data preprocessing configuration
preprocessing:
  remove_html: true
  remove_urls: true
  remove_emails: true
  remove_special_chars: true
  normalize_whitespace: true
  detect_language: false
  target_language: en
  language_confidence_threshold: 0.5
  min_doc_length: 10
  max_doc_length: 50000
  min_word_count: 3
  max_word_count: 10000
  se_relevance_threshold: 0.01
  se_keywords:
    - software
    - programming
    - algorithm
    - code
    - function
    - class
    - method
    - variable
    - database
    - framework
    - library
    - api
    - development
    - engineering
    - computer
    - system
    - application
    - interface
    - architecture
    - design
    - python
    - javascript
    - java
    - react
    - tensorflow
    - machine
    - learning
    - data
    - web
    - technology
  remove_duplicates: false
  similarity_threshold: 0.95
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  random_seed: 42

# Word2Vec model configuration
word2vec:
  vector_size: 50
  window: 3
  min_count: 1
  workers: 2
  epochs: 3
  sg: 0
  hs: 0
  negative: 5
  alpha: 0.025
  min_alpha: 0.0001
  batch_size: 1000
  max_vocab_size: 5000
  classification:
    enabled: true
    test_size: 0.2
    random_state: 42

# ModernBERT model configuration
modernbert:
  model_name: "answerdotai/ModernBERT-base"
  max_length: 128
  batch_size: 2
  learning_rate: 2e-5
  num_epochs: 1
  warmup_steps: 10
  weight_decay: 0.01
  save_steps: 50
  eval_steps: 25
  logging_steps: 5
  gradient_accumulation_steps: 1
  fp16: false
  early_stopping_patience: 2
  early_stopping_threshold: 0.001

# Evaluation configuration
evaluation:
  tasks:
    classification: true
    similarity: true
    clustering: true
    analogies: true
    retrieval: true
    code_text_similarity: true
  classification:
    test_size: 0.2
    cv_folds: 2
    random_state: 42
  similarity:
    sample_size: 20
    similarity_threshold: 0.7
  clustering:
    n_clusters: 2
    sample_size: 20
  analogies:
    sample_size: 10
    top_k: 2
  retrieval:
    sample_size: 15
    top_k: 3
  code_text_similarity:
    sample_size: 10

# Reporting configuration
reporting:
  generate_comprehensive_report: true
  generate_summary_dashboard: true
  generate_visualizations: true
  figure_format: png
  figure_dpi: 100
  figure_size: [8, 6]
  include_model_details: true
  include_training_logs: true
  include_evaluation_metrics: true
  include_statistical_analysis: true

